const data = [
    {
      id: 1,
      title: "The Sun and Her Flowers",
      author: "Rupi Kaur",
      pages: 256,
      rating: 4.5,
      description: "A vibrant and transcendent journey about growth and healing, ancestry and honoring one’s roots, expatriation and rising up to find a home within yourself.",
      cover_picture_url: "https://m.media-amazon.com/images/I/71gE8ZF9FqL.jpg",
      category: 'poetry',
    },
    {
      id: 2,
      title: "Milk and Honey",
      author: "Rupi Kaur",
      pages: 208,
      rating: 4.4,
      description: "A collection of poetry and prose about survival, the experience of violence, abuse, love, loss, and femininity.",
      cover_picture_url: "https://m.media-amazon.com/images/I/71l9WWa-rXL._AC_UF1000,1000_QL80_.jpg",
      category: 'poetry',
    },
    {
      id: 3,
      title: "Pillow Thoughts",
      author: "Courtney Peppernell",
      pages: 272,
      rating: 4.3,
      description: "A collection of poetry and prose about heartbreak, love, and the raw emotions of life.",
      cover_picture_url: "https://m.media-amazon.com/images/I/61zMLFmndYL._AC_UF1000,1000_QL80_.jpg",
      category: 'poetry',
    },
    {
      id: 4,
      title: "Love Her Wild",
      author: "Atticus Poetry",
      pages: 240,
      rating: 4.2,
      description: "A collection of short, romantic poems about love, adventure, and the wild spirit of youth.",
      cover_picture_url: "https://m.media-amazon.com/images/I/61n9WhCMfSL._AC_UF1000,1000_QL80_.jpg",
      category: 'poetry',
    },
    {
      id: 5,
      title: "The Princess Saves Herself in This One",
      author: "Amanda Lovelace",
      pages: 156,
      rating: 4.1,
      description: "A poetry collection that explores life’s journey and the power of self-healing and self-discovery.",
      cover_picture_url: "https://m.media-amazon.com/images/I/61a0CjuJYPL._AC_UF1000,1000_QL80_.jpg",
      category: 'poetry',
    },
    {
      id: 6,
      title: "Falling Toward the Moon",
      author: "r.h. Sin and Robert M. Drake",
      pages: 224,
      rating: 4.3,
      description: "An inspiring and beautifully written collection of poetry that examines love, pain, and healing.",
      cover_picture_url: "https://m.media-amazon.com/images/I/81Ecw0yx0tL._AC_UF1000,1000_QL80_.jpg",
      category: 'poetry',
    },
    {
      id: 7,
      title: "Devotions: The Selected Poems of Mary Oliver",
      author: "Mary Oliver",
      pages: 480,
      rating: 4.8,
      description: "A collection of Mary Oliver's most beloved poems, showcasing her remarkable ability to connect readers to the natural world and the human spirit.",
      cover_picture_url: "https://m.media-amazon.com/images/I/71h7beJLwSL._AC_UF1000,1000_QL80_.jpg",
      category: 'poetry',
    },
    {
      id: 8,
      title: "Chasers of the Light: Poems from the Typewriter Series",
      author: "Tyler Knott Gregson",
      pages: 160,
      rating: 4.5,
      description: "A beautiful collection of poems and black-and-white photography celebrating love, hope, and the magic found in everyday moments.",
      cover_picture_url: "https://m.media-amazon.com/images/I/61k8yxCZGfL._AC_UF1000,1000_QL80_.jpg",
      category: 'poetry',
    },
    {
      id: 9,
      title: "The Dark Between Stars",
      author: "Atticus Poetry",
      pages: 240,
      rating: 4.4,
      description: "A stunning collection of poetry that explores heartbreak, love, and the bittersweet beauty of the human condition.",
      cover_picture_url: "https://m.media-amazon.com/images/I/91cmiYpMqEL.jpg",
      category: 'poetry',
    },
    {
      id: 10,
      title: "Whiskey Words & a Shovel I",
      author: "r.h. Sin",
      pages: 304,
      rating: 4.2,
      description: "A raw and emotional poetry collection that speaks to the pain of heartbreak and the power of resilience and love.",
      cover_picture_url: "https://cdn.kobo.com/book-images/75cbb710-9303-413d-aaac-33955968a767/353/569/90/False/whiskey-words-a-shovel-i.jpg",
      category: 'poetry',
    },
    {
        id: 11,
        title: "Dune",
        author: "Frank Herbert",
        pages: 412,
        rating: 4.7,
        description: "Set on the desert planet Arrakis, Dune explores themes of politics, religion, and the human connection to nature.",
        cover_picture_url: "https://m.media-amazon.com/images/I/71m91l0treL._UF1000,1000_QL80_.jpg",
        category: 'sci-fi',
    },
    {
        id: 12,
        title: "Ender's Game",
        author: "Orson Scott Card",
        pages: 324,
        rating: 4.6,
        description: "A young genius is trained in a military academy to fight against an alien race threatening humanity.",
        cover_picture_url: "https://m.media-amazon.com/images/I/81+IUsYtGTL._AC_UF1000,1000_QL80_.jpg",
        category: 'sci-fi',
    },
    {
        id: 13,
        title: "The Hitchhiker's Guide to the Galaxy",
        author: "Douglas Adams",
        pages: 216,
        rating: 4.8,
        description: "A comedic adventure through space with quirky characters and bizarre interstellar hijinks.",
        cover_picture_url: "https://m.media-amazon.com/images/I/71OPafHmyQL.jpg",
        category: 'sci-fi',
    },
    {
        id: 14,
        title: "Foundation",
        author: "Isaac Asimov",
        pages: 255,
        rating: 4.5,
        description: "A mathematician develops psychohistory, a tool to predict the future and save humanity from a dark age.",
        cover_picture_url: "https://m.media-amazon.com/images/I/81LT+V9G4IL._AC_UF1000,1000_QL80_.jpg",
        category: 'sci-fi',
    },
    {
        id: 15,
        title: "Neuromancer",
        author: "William Gibson",
        pages: 271,
        rating: 4.4,
        description: "A cyberpunk classic exploring artificial intelligence, cyberspace, and the blending of man and machine.",
        cover_picture_url: "https://m.media-amazon.com/images/I/81m-rJnUdRL._AC_UF1000,1000_QL80_.jpg",
        category: 'sci-fi',
    },
    {
        id: 16,
        title: "Snow Crash",
        author: "Neal Stephenson",
        pages: 440,
        rating: 4.3,
        description: "A hacker and pizza delivery driver uncovers a virtual reality virus that threatens to reshape society.",
        cover_picture_url: "https://m.media-amazon.com/images/I/71k8hM3jrTL._AC_UF1000,1000_QL80_.jpg",
        category: 'sci-fi',
    },
    {
        id: 17,
        title: "Brave New World",
        author: "Aldous Huxley",
        pages: 268,
        rating: 4.6,
        description: "A dystopian novel depicting a genetically engineered society controlled by technology and consumerism.",
        cover_picture_url: "https://upload.wikimedia.org/wikipedia/en/6/62/BraveNewWorld_FirstEdition.jpg",
        category: 'sci-fi',
    },
    {
        id: 18,
        title: "The Martian",
        author: "Andy Weir",
        pages: 369,
        rating: 4.7,
        description: "An astronaut stranded on Mars uses ingenuity and science to survive and attempt rescue.",
        cover_picture_url: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1413706054i/18007564.jpg",
        category: 'sci-fi',
    },
    {
        id: 19,
        title: "Hyperion",
        author: "Dan Simmons",
        pages: 482,
        rating: 4.5,
        description: "A pilgrimage to the planet Hyperion reveals tales of love, betrayal, and mystery surrounding the Shrike.",
        cover_picture_url: "https://m.media-amazon.com/images/I/91V0S0qjKwL._AC_UF1000,1000_QL80_.jpg",
        category: 'sci-fi',
    },
    {
        id: 20,
        title: "Altered Carbon",
        author: "Richard K. Morgan",
        pages: 376,
        rating: 4.3,
        description: "In a future where consciousness can be transferred, a detective investigates a mysterious death.",
        cover_picture_url: "https://m.media-amazon.com/images/I/B13gH8nPGsS._AC_UF350,350_QL50_.jpg",
        category: 'sci-fi',
    },
    {
        id: 21,
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        pages: 180,
        rating: 4.7,
        description: "A classic novel set in the Jazz Age, exploring themes of wealth, love, and the American Dream.",
        cover_picture_url: "https://m.media-amazon.com/images/I/81Q6WkLhX4L._UF1000,1000_QL80_.jpg",
        category: 'fiction',
    },
    {
        id: 22,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        pages: 281,
        rating: 4.9,
        description: "A gripping and heartwarming story of justice, racial inequality, and moral growth in the American South.",
        cover_picture_url: "https://m.media-amazon.com/images/I/81gepf1eMqL._AC_UF1000,1000_QL80_.jpg",
        category: 'fiction',
    },
    {
        id: 23,
        title: "1984",
        author: "George Orwell",
        pages: 328,
        rating: 4.8,
        description: "A dystopian novel that delves into themes of totalitarianism, surveillance, and freedom.",
        cover_picture_url: "https://m.media-amazon.com/images/I/71rpa1-kyvL.jpg",
        category: 'fiction',
    },
    {
        id: 24,
        title: "Pride and Prejudice",
        author: "Jane Austen",
        pages: 279,
        rating: 4.6,
        description: "A timeless romance novel that explores class, love, and societal expectations in 19th century England.",
        cover_picture_url: "https://m.media-amazon.com/images/I/712P0p5cXIL._AC_UF1000,1000_QL80_.jpg",
        category: 'fiction',
    },
    {
        id: 25,
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        pages: 277,
        rating: 4.3,
        description: "A story of teenage rebellion and alienation, following the journey of Holden Caulfield.",
        cover_picture_url: "https://m.media-amazon.com/images/I/8125BDk3l9L._AC_UF1000,1000_QL80_.jpg",
        category: 'fiction',
    },
    {
        id: 26,
        title: "The Road",
        author: "Cormac McCarthy",
        pages: 287,
        rating: 4.5,
        description: "A post-apocalyptic novel about a father and son\’s survival in a desolate world.",
        cover_picture_url: "https://m.media-amazon.com/images/I/81ChFcmhXDL._AC_UF1000,1000_QL80_.jpg",
        category: 'fiction',
    },
    {
        id: 27,
        title: "The Alchemist",
        author: "Paulo Coelho",
        pages: 208,
        rating: 4.7,
        description: "A philosophical tale about following one's dreams and listening to one's heart.",
        cover_picture_url: "https://m.media-amazon.com/images/I/61HAE8zahLL._AC_UF1000,1000_QL80_.jpg",
        category: 'fiction',
    },
    {
        id: 28,
        title: "Animal Farm",
        author: "George Orwell",
        pages: 112,
        rating: 4.6,
        description: "A satirical allegory about the rise of totalitarianism, told through the lives of farm animals.",
        cover_picture_url: "https://m.media-amazon.com/images/I/71JUJ6pGoIL.jpg",
        category: 'fiction',
    },
    {
        id: 29,
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        pages: 310,
        rating: 4.8,
        description: "A fantasy adventure about Bilbo Baggins and his quest to help a group of dwarves reclaim their homeland.",
        cover_picture_url: "https://m.media-amazon.com/images/I/71jKeGU9nKL._AC_UF1000,1000_QL80_.jpg",
        category: 'fiction',
    },
    {
        id: 30,
        title: "The Kite Runner",
        author: "Khaled Hosseini",
        pages: 372,
        rating: 4.9,
        description: "A poignant story of friendship, betrayal, and redemption set against the backdrop of Afghanistan’s tumultuous history.",
        cover_picture_url: "https://m.media-amazon.com/images/I/81IzbD2IiIL._AC_UF1000,1000_QL80_.jpg",
        category: 'fiction',
    },
    {
        id: 31,
        title: "Sapiens: A Brief History of Humankind",
        author: "Yuval Noah Harari",
        pages: 443,
        rating: 4.7,
        description: "An exploration of how Homo sapiens came to dominate the world, from the cognitive revolution to the present day.",
        cover_picture_url: "https://m.media-amazon.com/images/I/713jIoMO3UL.jpg",
        category: 'non-fiction',
    },
    {
        id: 32,
        title: "Educated",
        author: "Tara Westover",
        pages: 334,
        rating: 4.8,
        description: "A memoir about a young girl who grew up in a strict and abusive household in rural Idaho, and her journey to education and self-liberation.",
        cover_picture_url: "https://m.media-amazon.com/images/I/71-4MkLN5jL._AC_UF1000,1000_QL80_.jpg",
        category: 'non-fiction',
    },
    {
        id: 33,
        title: "The Immortal Life of Henrietta Lacks",
        author: "Rebecca Skloot",
        pages: 381,
        rating: 4.6,
        description: "The story of Henrietta Lacks, whose cells were taken without her knowledge in 1951, becoming one of the most important tools in medicine.",
        cover_picture_url: "https://m.media-amazon.com/images/I/81coyP8S-ZL._AC_UF1000,1000_QL80_.jpg",
        category: 'non-fiction',
    },
    {
        id: 34,
        title: "Thinking, Fast and Slow",
        author: "Daniel Kahneman",
        pages: 499,
        rating: 4.7,
        description: "A deep dive into the dual systems of thinking—fast, intuitive thinking, and slow, deliberate thinking—and how they affect decision-making.",
        cover_picture_url: "https://m.media-amazon.com/images/I/71f6DceqZAL._AC_UF1000,1000_QL80_.jpg",
        category: 'non-fiction',
    },
    {
        id: 35,
        title: "Becoming",
        author: "Michelle Obama",
        pages: 426,
        rating: 4.8,
        description: "A memoir detailing Michelle Obama’s experiences from her childhood in Chicago to her time as First Lady of the United States.",
        cover_picture_url: "https://m.media-amazon.com/images/I/81KGjsBXQ7L._AC_UF1000,1000_QL80_.jpg",
        category: 'non-fiction',
    },
    {
        id: 36,
        title: "The Body: A Guide for Occupants",
        author: "Bill Bryson",
        pages: 448,
        rating: 4.5,
        description: "An exploration of the human body, detailing its functions, systems, and the history of how we’ve come to understand it.",
        cover_picture_url: "https://m.media-amazon.com/images/I/61UPbEk3zmL._AC_UF1000,1000_QL80_.jpg",
        category: 'non-fiction',
    },
    {
        id: 37,
        title: "Sapiens: A Graphic History, Volume 1",
        author: "Yuval Noah Harari, David Vandermeulen, Daniel Casanave",
        pages: 224,
        rating: 4.5,
        description: "A graphic adaptation of the original Sapiens, presenting the story of human evolution through visuals.",
        cover_picture_url: "https://m.media-amazon.com/images/I/81T5QjnQa7S._UF1000,1000_QL80_.jpg",
        category: 'non-fiction',
    },
    {
        id: 38,
        title: "The Wright Brothers",
        author: "David McCullough",
        pages: 320,
        rating: 4.6,
        description: "A biography of the Wright brothers, detailing their pioneering achievements in aviation.",
        cover_picture_url: "https://m.media-amazon.com/images/I/71TYHByzngL._AC_UF1000,1000_QL80_.jpg",
        category: 'non-fiction',
    },
    {
        id: 39,
        title: "The Power of Habit",
        author: "Charles Duhigg",
        pages: 402,
        rating: 4.6,
        description: "An exploration of how habits are formed and how they can be changed to improve productivity and personal well-being.",
        cover_picture_url: "https://m.media-amazon.com/images/I/71ONWR6eXDL.jpg",
        category: 'non-fiction',
    },
    {
        id:  41,
        title: "The Girl with the Dragon Tattoo",
        author: "Stieg Larsson",
        pages: 672,
        rating: 4.5,
        description: "A gripping mystery novel that follows journalist Mikael Blomkvist and hacker Lisbeth Salander as they unravel a decades-old disappearance.",
        cover_picture_url: "https://m.media-amazon.com/images/I/81YW99XIpJL._UF1000,1000_QL80_.jpg",
        category: 'mystery',
      },
      {
        id:  42,
        title: "Gone Girl",
        author: "Gillian Flynn",
        pages: 432,
        rating: 4.6,
        description: "A psychological thriller that delves into a twisted marriage and a mysterious disappearance that unravels dark secrets.",
        cover_picture_url: "https://m.media-amazon.com/images/I/71+khXHbe5L._AC_UF1000,1000_QL80_.jpg",
        category: 'mystery',
      },
      {
        id:  43,
        title: "The Silent Patient",
        author: "Alex Michaelides",
        pages: 336,
        rating: 4.7,
        description: "A compelling psychological mystery about a woman who stops speaking after being accused of her husband’s murder.",
        cover_picture_url: "https://m.media-amazon.com/images/I/81JJPDNlxSL.jpg",
        category: 'mystery',
      },
      {
        id: 44,
        title: "The Hound of the Baskervilles",
        author: "Arthur Conan Doyle",
        pages: 256,
        rating: 4.4,
        description: "A classic Sherlock Holmes mystery involving a dark legend and a family curse on the Baskerville estate.",
        cover_picture_url: "https://m.media-amazon.com/images/I/71G3Fs2IEIL._AC_UF1000,1000_QL80_.jpg",
        category: 'mystery',
      },
      {
        id: 45,
        title: "The Woman in the Window",
        author: "A.J. Finn",
        pages: 448,
        rating: 4.3,
        description: "A suspenseful thriller about an agoraphobic woman who becomes obsessed with her neighbor's mysterious life.",
        cover_picture_url: "https://m.media-amazon.com/images/I/7196sTeTolL._AC_UF1000,1000_QL80_.jpg",
        category: 'mystery',
      },
      {
        id: 46,
        title: "In the Woods",
        author: "Tana French",
        pages: 512,
        rating: 4.5,
        description: "A chilling debut novel that follows a detective unraveling the dark secrets of a town after a murder investigation.",
        cover_picture_url: "https://m.media-amazon.com/images/I/71OjMeKpdmL.jpg",
        category: 'mystery',
      },
      {
        id: 47,
        title: "The Da Vinci Code",
        author: "Dan Brown",
        pages: 592,
        rating: 4.2,
        description: "A fast-paced conspiracy thriller involving art, history, and secret societies as Robert Langdon solves a mystery.",
        cover_picture_url: "https://m.media-amazon.com/images/I/71y4X5150dL.jpg",
        category: 'mystery',
      },
      {
        id: 48,
        title: "Big Little Lies",
        author: "Liane Moriarty",
        pages: 464,
        rating: 4.4,
        description: "A mystery unraveling the secrets of a wealthy seaside town, filled with lies, betrayal, and murder.",
        cover_picture_url: "https://m.media-amazon.com/images/I/71l2dN4K4vL._AC_UF350,350_QL50_.jpg",
        category: 'mystery',
      },
      {
        id: 49,
        title: "The Thirteenth Tale",
        author: "Diane Setterfield",
        pages: 528,
        rating: 4.3,
        description: "A captivating mystery revolving around a biographer unraveling the truth behind a reclusive author’s strange past.",
        cover_picture_url: "https://m.media-amazon.com/images/I/81TVVmmO85L.jpg",
        category: 'mystery',
      },
      {
        id: 50,
        title: "The Night Circus",
        author: "Erin Morgenstern",
        pages: 400,
        rating: 4.6,
        description: "A spellbinding tale of magic and mystery, where two young illusionists face off in a mysterious competition.",
        cover_picture_url: "https://m.media-amazon.com/images/I/71+whvJjE3L._AC_UF1000,1000_QL80_.jpg",
        category: 'mystery',
      },
];

export default data;
  